"""Acceso a datos con SQL portable: PostgreSQL (Docker) y SQLite (pruebas locales rápidas).

Los placeholders se escriben como ``?`` y se traducen según el motor. Las transacciones
son explícitas (``with conn.tx():``) para que el comportamiento sea idéntico en ambos.
"""
import sqlite3
import time
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

try:  # psycopg solo es obligatorio dentro de Docker
    import psycopg
    from psycopg.rows import dict_row

    _PgIntegrity = psycopg.errors.IntegrityError
except ImportError:  # pragma: no cover
    psycopg = None
    dict_row = None

    class _PgIntegrity(Exception):
        pass


IntegrityError = (sqlite3.IntegrityError, _PgIntegrity)
MIGRACIONES = Path(__file__).parent / "migraciones"


def ahora():
    """Fecha/hora UTC sin zona, sin microsegundos."""
    return datetime.now(timezone.utc).replace(tzinfo=None, microsecond=0)


def es_sqlite(url):
    return url.startswith("sqlite")


def nombre_bd(url):
    if es_sqlite(url):
        return Path(url.replace("sqlite:///", "", 1)).name
    return urlparse(url).path.lstrip("/")


class Conexion:
    def __init__(self, url):
        self.url = url
        self.sqlite = es_sqlite(url)
        if self.sqlite:
            ruta = url.replace("sqlite:///", "", 1)
            self.con = sqlite3.connect(ruta, isolation_level=None, timeout=15)
            self.con.row_factory = sqlite3.Row
            self.con.execute("PRAGMA foreign_keys = ON")
        else:
            if psycopg is None:
                raise RuntimeError("psycopg no está instalado")
            self.con = psycopg.connect(url, autocommit=True, row_factory=dict_row)
        self._en_tx = False

    # -- utilidades -----------------------------------------------------------
    def _sql(self, sql):
        return sql if self.sqlite else sql.replace("%", "%%").replace("?", "%s")

    def _params(self, params):
        if not self.sqlite:
            return tuple(params)
        return tuple(p.strftime("%Y-%m-%d %H:%M:%S") if isinstance(p, datetime) else p for p in params)

    def _exec(self, sql, params=()):
        return self.con.execute(self._sql(sql), self._params(params))

    # -- API ------------------------------------------------------------------
    def consultar(self, sql, params=()):
        return [dict(r) for r in self._exec(sql, params).fetchall()]

    def uno(self, sql, params=()):
        filas = self.consultar(sql, params)
        return filas[0] if filas else None

    def valor(self, sql, params=()):
        fila = self.uno(sql, params)
        return next(iter(fila.values())) if fila else None

    def ejecutar(self, sql, params=()):
        return self._exec(sql, params).rowcount

    def insertar(self, sql, params=()):
        return self.uno(sql + " RETURNING id", params)["id"]

    @contextmanager
    def tx(self):
        if self._en_tx:  # transacción anidada: participa de la externa
            yield self
            return
        self.con.execute("BEGIN")
        self._en_tx = True
        try:
            yield self
        except BaseException:
            self.con.execute("ROLLBACK")
            raise
        else:
            self.con.execute("COMMIT")
        finally:
            self._en_tx = False

    def cerrar(self):
        try:
            self.con.close()
        except Exception:  # pragma: no cover
            pass


def esperar_bd(url, intentos=40, pausa=1.5):
    """Espera a que la base de datos acepte conexiones (arranque con dependencias)."""
    ultimo = None
    for _ in range(intentos):
        try:
            c = Conexion(url)
            c.valor("SELECT 1")
            c.cerrar()
            return
        except Exception as exc:  # noqa: BLE001
            ultimo = exc
            time.sleep(pausa)
    raise RuntimeError(f"La base de datos no respondió: {ultimo}")


def _traducir(sql, sqlite):
    pk = "INTEGER PRIMARY KEY AUTOINCREMENT" if sqlite else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return sql.replace("{{PK}}", pk).replace("{{TS}}", "TIMESTAMP")


def migrar(conn):
    """Aplica las migraciones pendientes en orden. Idempotente."""
    conn.ejecutar("CREATE TABLE IF NOT EXISTS migraciones (version VARCHAR(100) PRIMARY KEY, aplicada TIMESTAMP NOT NULL)")
    hechas = {r["version"] for r in conn.consultar("SELECT version FROM migraciones")}
    aplicadas = []
    for archivo in sorted(MIGRACIONES.glob("*.sql")):
        if archivo.stem in hechas:
            continue
        sentencias = [s.strip() for s in _traducir(archivo.read_text(encoding="utf-8"), conn.sqlite).split(";") if s.strip()]
        with conn.tx():
            for s in sentencias:
                conn.ejecutar(s)
            conn.ejecutar("INSERT INTO migraciones (version, aplicada) VALUES (?, ?)", (archivo.stem, ahora()))
        aplicadas.append(archivo.stem)
    from .catalogos import asegurar_catalogos

    asegurar_catalogos(conn)
    return aplicadas


def reiniciar_bd_de_pruebas(url):
    """Destruye y recrea el esquema. SOLO permitido si el nombre de la BD contiene 'test'."""
    if "test" not in nombre_bd(url).lower():
        raise RuntimeError(f"Se rechaza reiniciar '{nombre_bd(url)}': no parece una base de pruebas.")
    conn = Conexion(url)
    try:
        if conn.sqlite:
            conn.cerrar()
            ruta = Path(url.replace("sqlite:///", "", 1))
            if ruta.exists():
                ruta.unlink()
            conn = Conexion(url)
        else:
            conn.ejecutar("DROP SCHEMA public CASCADE")
            conn.ejecutar("CREATE SCHEMA public")
        migrar(conn)
    finally:
        conn.cerrar()
